spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/plants_journal
    username: postgres
    password: postgres
    initialization-mode: always
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

springdoc:
  api-docs:
    path: /journal-openapi